---
- name: Check presence of fastestmirror.conf
  stat:
    path: /etc/yum/pluginconf.d/fastestmirror.conf
  register: fastestmirror

# fastestmirror plugin actually slows down Ansible deployments
- name: Disable fastestmirror plugin
  lineinfile:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    regexp: "^enabled=.*"
    line: "enabled=0"
    state: present
  become: true
  when: fastestmirror.stat.exists

- name: remove centos firewall pkg
  yum: 
    name: 
      - firewalld
      - python-firewall
      - firewalld-filesystem
#      - container-selinux
      - dnsmasq
      - nscd
    state: absent

- name: disable selinux
  shell: "setenforce 0"
  failed_when: false

- name: disable selinux forover
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: disable rsyslog get journald
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: 'ModLoad imjournal'
    line: '#$ModLoad imjournal # provides access to the systemd journal'

- name: Create the yum source backup folder
  file: path=/etc/yum.repos.d/backup state=directory
  when: ansible_os_family == 'RedHat' and install_type == "offline"

- name: Delete default CentOS source
  shell: mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup
  when: ansible_os_family == 'RedHat' and install_type == "offline"

- name:  Add Offline CentOS Repository
  template: src=glusterfs.repo.j2 dest=/etc/yum.repos.d/glusterfs.repo
  when: ansible_os_family == 'RedHat' and install_type == "offline"

- name: Copy pkgs into /opt/glusterfs
  copy:
    src: /opt/glusterfs/pkgs
    dest: /opt/glusterfs
  when: ansible_os_family == 'RedHat' and install_type == "offline"

- name: Clear default cache
  command: yum clean all
  args:
    warn: no
  when: ansible_os_family == 'RedHat' and install_type == "offline"