---
- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: RedHat-offline.yml
  when: ansible_os_family == 'RedHat' and install_type == 'offline'

- import_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: Debian-offline.yml
  when: ansible_os_family == 'Debian' and install_type == 'offline'