---
- name: Install Prerequisites
  yum: 
    name:
      - "centos-release-gluster{{ glusterfs_default_release }}"
    state: present

- name: Install Packages
  yum: 
    name:
      - glusterfs-server-6.0-1.el7
      - glusterfs-client-6.0-1.el7
  state: present


